### ISSUE TITLE
Understand Skeleton Docs

### ISSUE THREAD

**Issue by grayad** [grayad/habit-rabbit#3]

**Comment by aMcCode** [comment]
Please see code at https://github.com/aMcCode/skeleton-css-exploration/tree/develop. I copied Hannah's index.html and css into that repo and "Skeletonarized" it. The biggest gain is I was able to drop the media queries. You'll also see my team-generator html and css in that repo. I think the card structure for our second html page will be similar. Feel free to clone the repo and view the html files locally. The responsiveness of the card layout is impressive.

You can find a good overview of Skeleton here: http://getskeleton.com/, but I'll also do a quick walk through when we meet if you like.
